server:
    port: 8080
spring:
    application:
        name: order-service
    datasource:
        driver-class-name: org.postgresql.Driver
        password: 123456
        url: jdbc:postgresql://localhost:5432/order_service
        username: postgres
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8686/eureka/
        fetch-registry: true
        register-with-eureka: true
