spring:
  application:
    name: pharmacy-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pharmacy_db
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: order-event:com.trung.pharmacyservice.event.OrderEvent
server:
  port: 8081
  
management:
  endpoints:
    web:
      exposure:
        include: refresh, health

app:
  branch-name: Nha Thuoc So 1
  hotline: 19001234

pharmacy:
  vat-rate: 0.2

resilience4j:
  circuitbreaker:
    instances:
      warehouseCB:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
      insuranceCB:
        failure-rate-threshold: 60
        wait-duration-in-open-state: 10s
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true

  ratelimiter:
    instances:
      invoiceRL:
        limit-for-period: 5
        limit-refresh-period: 10s
        timeout-duration: 0s
        rate-limiter-aspect-order: 1
        
  retry:
    instances:
      invoiceRetry:
        max-attempts: 3
        wait-duration: 2s
        retry-exceptions:
          - org.springframework.web.client.ResourceAccessException
          - java.net.ConnectException

      insuranceRetry:
        max-attempts: 3
        wait-duration: 2s
        retry-exceptions:
          - org.springframework.web.client.ResourceAccessException
          - java.net.ConnectException
        ignore-exceptions:
          - java.util.concurrent.TimeoutException

  timelimiter:
    instances:
      checkInsurance:
        timeout-duration: 0s
        cancel-running-future: true