services:
  postgres:
    image: postgres:16
    container_name: postgres-redis-demo
    environment:
      POSTGRES_DB: redis_demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7.2
    container_name: redis-spring-boot
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data: