spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: customer-service
              uri: lb://customer-service
              predicates:
                - Path=/api/v1/customers/**
              filters:
                - AddRequestHeader=X-Request-Source, Gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
server:
  port: 8888