spring.application.name=notification-service

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=trung8d2005@gmail.com
spring.mail.password=omguvfazmwrxoagv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true