spring.application.name=eureka-server-service
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=50MB


#C?u hình eureka server
server.port=8686
eureka.client.fetch-registry=false
eureka.client.register-with-eureka=false
#??a ch? c?a server eureka
eureka.client.service-url.defaultZone=http://localhost:8686/eureka/